### ISSUE TITLE
Resources

### ISSUE THREAD

**Issue by AliMoal** [eduds08/saft-algorithm-python#1]
Thank you for your implementation.
It would be great if you provide resources and articles you used for this algorithm.

**Comment by eduds08** [comment]
Hello! You're welcome, I'm glad someone liked it. I did it for a project in my college, 
I will try to grab all resources I've used.

**Comment by eduds08** [comment]
I've read these 2 articles and also got help from my teachers. My apologies for the delay.
https://www.sciencedirect.com/science/article/abs/pii/0041624X84900556?via%3Dihub
https://www.mdpi.com/1424-8220/15/4/9324

**Comment by AliMoal** [comment]
Thank you so much, It's really worthful and hopeful.
